FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir taipy==4.1.0 taipy-gui==4.1.0 taipy-core==4.1.0 taipy-common==4.1.0 taipy-rest==4.1.0 taipy-templates==4.1.0 duckdb==1.4.1 pandas==2.2.2 plotly==6.5.0 seaborn==0.13.2

COPY frontend/ /app/

EXPOSE 8081

CMD ["python", "dashboard.py"]