sources:
  - name: strength_table  # källans namn i dbt
    schema: staging        # schema i databasen
    tables:
      - name: stg_alex      # så här refererar du den i dbt
        identifier: stg_alex  # verkligt tabellnamn i databasen
      
      - name: stg_erik
        identifier: stg_erik